### ISSUE TITLE
Incorrect username in dashboard

### ISSUE THREAD

**Issue by ohsayan** [packetframe/legacy#2]
Under settings in the dashboard, the e-mail address is shown to be: `nate@delivr.dev` instead of the user's e-mail address, which I suspect is caused by this:
https://github.com/natesales/delivr/blob/64267feb760d286e3ab5aadaadcd8e82f7064f5e/frontend/src/components/Settings.svelte#L65

We need to show the user's e-mail and not yours 😄! See the attached image below:
![ss](https://user-images.githubusercontent.com/17377258/98900590-1c398680-24d8-11eb-91c5-0e72f06f3d06.png)

(...I'm glad to be a part of the private beta ).

**Comment by natesales** [comment]
Nice catch! The user's email isn't stored anywhere that's easy to access from the dashboard at the moment, so I've removed that line for now and added a component prop in preparation for the future where the email might be stored as a cookie. (https://github.com/natesales/delivr/commit/720ed2e519e62ee85da62150fff1d68b9976bc25)
